version: "3.8"
services:
  resource-service:
    build: ./resource-service
    ports:
      - "8081:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://resource-service-database:5432/${RESOURCE_DB_NAME}
      - DATABASE_USER=${RESOURCE_DB_USER}
      - DATABASE_PASSWORD=${RESOURCE_DB_PASSWORD}
      - EUREKA_URL=${SERVICE_DISCOVERY_URL}
    restart: always
    depends_on:
      - service-discovery
      - resource-service-database
      - song-service

  song-service:
    build: ./song-service
    ports:
      - "8082:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://song-service-database:5432/${SONG_DB_NAME}
      - DATABASE_USER=${SONG_DB_USER}
      - DATABASE_PASSWORD=${SONG_DB_PASSWORD}
      - EUREKA_URL=${SERVICE_DISCOVERY_URL}
    restart: always
    depends_on:
      - service-discovery
      - song-service-database

  service-discovery:
    build: ./service-discovery
    ports:
      - "8761:8761"
    restart: always

  resource-service-database:
    image: postgres:16.1-bullseye
    ports:
      - "54321:5432"
    volumes:
      - resource-service-database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${RESOURCE_DB_NAME}
      - POSTGRES_USER=${RESOURCE_DB_USER}
      - POSTGRES_PASSWORD=${RESOURCE_DB_PASSWORD}
    restart: always

  song-service-database:
    image: postgres:16.1-bullseye
    ports:
      - "54322:5432"
    volumes:
      - song-service-database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${SONG_DB_NAME}
      - POSTGRES_USER=${SONG_DB_USER}
      - POSTGRES_PASSWORD=${SONG_DB_PASSWORD}
    restart: always
volumes:
  resource-service-database:
  song-service-database: