server:
  error:
    include-stacktrace: never
spring:
  application:
    name: resource-processor
  rabbitmq:
    host: message-broker
    username: ${BROKER_USERNAME}
    password: ${BROKER_PASSWORD}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
message:
  broker:
    exchange: ${BROKER_EXCHANGE}
    routing-key: ${BROKER_ROTING_KEY}
    queue: ${BROKER_QUEUE}
resource:
  service:
    client:
      scheme: http
      service-id: RESOURCE-SERVICE
      endpoint: resources/{id}
song:
  service:
    client:
      scheme: http
      service-id: SONG-SERVICE
      endpoint: songs