server:
  port: 8081
  error:
    include-stacktrace: never
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:54322/song
    username: postgres
    password: root
logging:
  level:
    by.latushka: debug