server:
  error:
    include-stacktrace: never
spring:
  application:
    name: song-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  rabbitmq:
    host: message-broker
    username: ${BROKER_USERNAME}
    password: ${BROKER_PASSWORD}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
message:
  broker:
    exchange: ${BROKER_EXCHANGE}
    routing-key: ${BROKER_ROTING_KEY}
    queue: ${BROKER_QUEUE}
logging:
  level:
    by.latushka: debug