server:
  error:
    include-stacktrace: never
spring:
  application:
    name: song-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
logging:
  level:
    by.latushka: debug