server:
  error:
    include-stacktrace: never
spring:
  application:
    name: resource-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    hikari:
      auto-commit: false
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
song:
  service:
    client:
        scheme: http
        host: song-service
        port: 8080
        endpoint: songs
logging:
  level:
    by.latushka: debug