server:
  error:
    include-stacktrace: never
spring:
  application:
    name: resource-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    hikari:
      auto-commit: false
  rabbitmq:
    host: message-broker
    username: ${BROKER_USERNAME}
    password: ${BROKER_PASSWORD}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
minio:
  endpoint: http://minio-service:9000
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket-name: mp3bucket
logging:
  level:
    by.latushka: debug
message:
  broker:
    exchange: ${BROKER_EXCHANGE}
    upload-routing-key: ${BROKER_UPLOAD_ROTING_KEY}
    delete-routing-key: ${BROKER_DELETE_ROTING_KEY}